### ISSUE TITLE
RADKLIM radar data do not properly read

### ISSUE THREAD

**Issue by lochbika** [brry/dwdradar#5]
I forked the repo and added YW (radklim) to the list of products in the readradarfile function. See my pull request there...
https://github.com/lochbika/dwdradar/pull/1

**Comment by brry** [comment]
Hi Kai,
I'm perfectly happy to add that. Could you send a url on the ftp server where this applies, so I can expand the automated testing?

**Comment by lochbika** [comment]
Hi Berry,
nice. The radklim files for 5 minute precipitation can be found here (the ascii and binary version): https://opendata.dwd.de/climate_environment/CDC/grids_germany/5_minutes/radolan/reproc/2017_002/
Surprisingly they are in the radolan folder, but they are actually from the radklim data set. 
I only changed the R code for this type of product.

Then, there is also a version with hourly data (product RW): https://opendata.dwd.de/climate_environment/CDC/grids_germany/hourly/radolan/reproc/2017_002/ 

Another thing that is different from the radolan data set is the domain size and extent. You can read everything about it here (unfortunately in German):
https://www.dwd.de/DE/leistungen/radarklimatologie/radklim_kompositformat_1_0.pdf?__blob=publicationFile&v=1

One final thing. I directly used the readradarfile routine from the dwdradar package, without the rdwd package functions. I guess that you need to change some code in the rdwd package code, too, to support the radklim data set.

Finally, I want to say that your package saved a great amount of time for me, great work, thank you!

Cheers

**Comment by brry** [comment]
Hi Kai,
I got around to implementing the changes in both packages. You can update with
```r
rdwd::updateRdwd("dwdradar")
rdwd::updateRdwd()
```
Feel free to use `dwdradar` if that suits your workflow. Note that `rdwd` contains some nice code to handle unzipping the two tar layers, see https://github.com/brry/rdwd/blob/master/man/readDWD.rklim.Rd.

I could not find the extent and projection information in the radklim doc, but played around with a manual extent that seems to fit the radar locations (see the examples at the mentioned url). Feel free to add the information if needed.

Please let me know if any bugs come up ;)
